### ISSUE TITLE
文本框优化

### ISSUE THREAD

**Issue by Gradus9684** [tsingyayin/cYSP#7]
名称右侧右移0.052上移0.01
文本左侧右移0.04上移0.01
文本字体增大15%，行距对于中文字来说是0.5倍
![新建画布1](https://user-images.githubusercontent.com/97093562/163676779-3c0a12d9-497d-49eb-93f5-0b60927842df.jpg)

**Comment by tsingyayin** [comment]
新效果会在调试完毕之后在Arknights.ceui中应用。
ysp原版位置不再做出更改。现在的问题在于，缩小WordLabel可能导致换行不正确，需要更改内核换行算法。期望算法是将换行交由qlabel自动完成。

**Comment by tsingyayin** [comment]
弄好了，加入下次的更新。
